### ISSUE TITLE
https certificate fails to renew and expires

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_arcsi#119]
**Bug**: `certbot` container fails to renew certificate. 

**Reason (w/ certbot's webroot)**: `webroot` path is not a joint volume across the `nginx` and `certbot` containers. As a result, the http challenge via `webroot` cannot be checked by Letsencrypt. 

**Reason (w/ cerbot's standalone)**: it's not an ideal solution for is cause `nginx` is using port 80 so the system would need to be shut down upon renewal (see https://advancedweb.hu/when-to-use-lets-encrypts-webroot-and-standalone-authorization/).

**Comment by auracherS** [comment]
I had a similar problem 
humhub server failed to renew the SSL certificate
the reaseon is that the recommended installation from
https://docs.humhub.org/docs/admin/server-setup/
recomends
apt install certbot
certbot certonly --standalone -d temp.humhub.dev
This is ok for first instalaltion. Especially tomhave an SSL certificate befor the webserver is installed. But after 30 days, at this pint my SSL certificate timed out. The server tried an automatic renewal (daily cron job). But with the option certbot --standalone (with the standalon authenticator) this can not work because port 80 is already used by the server. 
I am using nginx not apache as webserver.

My solution was: I installed another cerbot authenticator. Instead of standalone there exists is an authenticator, which uses nginx. it can be installad as follows:

apt install python-certbot-nginx

I changed the setup file /etc/letsencrypt/renewal/mydomain.conf
mydomain.conf here is just a placeholder
I outcommented the old authenticator
# authenticator = standalone
and inserted the new one
authenticator = nginx

now the manual renewal with
certbot renew
works

the new certificaste has to be reloaded:
/etc/init.d/nginx reload

now the new certificate is online 

to have this to work automatically with the already existing cron job I changed the cron line also
In /etc/cron.d/certbot I outcommented the old line
# 0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew
and inserted a new one
0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew --renew-hook "/etc/init.d/nginx reload"

I hope the next automatic renewal works. I think the docu under https://docs.humhub.org/docs/admin/server-setup/ shall be corrected in the above way. But also there might be a better way to do this as described here.
https://www.guyrutenberg.com/2017/01/01/lets-encrypt-reload-nginx-after-renewing-certificates/

best wishes

**Comment by gammaw** [comment]
@auracherS thanks. We already have a webserver in place so we can use the `webroot` authenticator method.

**Comment by gammaw** [comment]
Final note: a new `certbot certonly --webroot ...` command was enough (there was no need to delete or to renew the existing), as a result, the cert has been renewed and the authenticator has been changed from `standalone` to `webroot`.

**Comment by gammaw** [comment]
Final final note (lesson learnt): you'll need to restart the web server so that it serves the renewed certificate.
