### ISSUE TITLE
Improve arcsi rest endpoints

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun_arcsi#123]
Just checked the swagger, nice job @tuz666 !
Would be nice to have a `shows/all?=basic` (or some other name) that would give back just the basic shows data (`name, description, time...`), without all the items (arcsi episodes). That would make the basic request for the ananasz calls much smaller.
For `item` (episode) would it be possible to have a queryable `slug` endpoint, so they can be queried also by this, not only the `id`? Also, if possible to have a `listening_count` besides `download_count` in response > don't know how it works in either case, how it counts this... At this query, it would be nice to have the `archive_lahmastore_base_url` at the `shows` array entries.

**Comment by pvj** [comment]
Sorry for not responding here @baxgas 

Good suggestions. We are already looking into the first, trying to work out the cleanest solution. We might simply just not add the episodes to shows or list only their ids, instead of the full-blown object. We'll see and let you know.

Second suggestion is something we already do, no? If you check the items under a show, you get the same results as querying slug on items. Maybe I don't correctly understand the question. Sorry but please elaborate in that case.

>At this query, it would be nice to have the archive_lahmastore_base_url at the shows array entries.
Sorry, I might not understand this correctly. Do you want each show object to contain a self-reference?

We will be adding all these you asked or something very similar. 

If you can just help me bit with explanation that would be splendid. Thanks so much~~

**Comment by pvj** [comment]
@baxgas please take a look at @tuz666 's nice PR and let us know what you think from the front-end side please

**Comment by baxgas** [comment]
Thanks @pvj

**Comment by gammaw** [comment]
Great efforts!

Can you help me to understand a couple of things. 

@baxgas writes:
> For item (episode) would it be possible to have a queryable slug endpoint, so they can be queried also by this, not only the id?

Why is this needed (query by slug vs query by ID)?  

@tuz666 writes (in the PR):
> added a new route /show_slug/episode_number where we can query the specified item directly

Don't you mean `/show_slug/episode_slug`?

**Comment by pvj** [comment]
>Also, if possible to have a listening_count besides download_count in response > don't know how it works in either case, how it counts this... At this query, it would be nice to have the archive_lahmastore_base_url at the shows array entries.

I'll move this to a separate ticket because it's schema-related update to add `listening_count` 

Otherwise we merged this PR #127 just now so all others requests are done:

For the `show/all` we now only return: 

`"id", "active", "name", "description",
                                                         "week", "day", "start", "end",
                                                         "cover_image_url", "archive_lahmastore_base_url"`

We introduced a new endpoint: 

`show/<string:show_slug>/episode/<string:episode_slug>`

**Comment by pvj** [comment]
Congrats @tuz666 and many eternal hails!
